"""start

Revision ID: f17dab6c5961
Revises: 
Create Date: 2021-08-18 11:30:00.050006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17dab6c5961'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('doc_number', sa.VARCHAR(length=30), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_table(
        'order_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=True, comment='Заказ'),
        sa.Column('product_name', sa.VARCHAR(length=30), nullable=True),
        sa.Column('amount', sa.Integer(), nullable=True),
        sa.Column('price', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
